name: "Internxt WebDAV"
version: "1.0.0"
slug: "internxt_webdav"
description: "WebDAV server for Internxt cloud storage"
url: "https://github.com/cgfm/internxt-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
boot: auto
hassio_api: true
hassio_role: default
ports:
  3005/tcp: 3005
ports_description:
  3005/tcp: WebDAV server port
options:
  inxt_user: ""
  inxt_password: ""
  inxt_twofactorcode: ""
  inxt_otptoken: ""
  webdav_port: 3005
  webdav_protocol: "https"
schema:
  inxt_user: email
  inxt_password: password
  inxt_twofactorcode: str?
  inxt_otptoken: str?
  webdav_port: port
  webdav_protocol: list(http|https)
